### ISSUE TITLE
Correct power management missing

### ISSUE THREAD

**Issue by 1alessandro1** [mbarbierato/Intel-NUC8i3BEH#3]
Hi, the use of the patch `AppleXcpmCfgLock` is highly **discouraged** as can cause all kinds of system instability due to the fact that patching `AppleIntelCPUPowerManagement.kext` is a very bad idea.

https://github.com/mbarbierato/Intel-NUC8i3BEH/blob/374ed1adb8c8771edd55eb58777a67a2c9bee15c/EFI/OC/Config.plist#L408-L409

Also, SuperIO sensor reading support [in your case, Intel_EC_V8] has been added for NUCs, check out this page:

https://github.com/acidanthera/VirtualSMC/blob/master/Docs/EmbeddedControllers.md

In your case, the sample patch matches your NUC model. A deviceproperty patch is all you need, alongside the latest VirtualSMC build coming on April 5th or from [here](https://github.com/dortania/build-repo/releases/download/VirtualSMC-554b288/VirtualSMC-1.2.2-RELEASE.zip)

```
<key>PciRoot(0x0)/Pci(0x1f,0x0)</key>
		<dict>
			<key>ec-device</key>
			<string>Intel_EC_V8</string>
			<key>model</key>
			<string>Intel Corporation Coffee Lake Series LPC Controller</string>
		</dict>
```

**Comment by mbarbierato** [comment]
HI I've read this and the osy's pr 
i'm already testing this patch on my machine and when kext is released i will update the repo
Thank you

**Comment by 1alessandro1** [comment]
Check out `ControlMsrE2.efi` to unlock the MSR 0xE2 register, it is under the `Tools` folder
To use that, you have to enter a shell and launch that (you can use OpenShell.efi which is already built in inside)

https://github.com/dortania/build-repo/releases/download/OpenCorePkg-423defd/OpenCore-0.6.8-RELEASE.zip

**Comment by zearp** [comment]
@1alessandro1 do you own this model of NUC? Sounds like you don’t.
