### ISSUE TITLE
[Request for Info] How to enable mSD card reader?

### ISSUE THREAD

**Issue by woody4165** [mbarbierato/Intel-NUC8i3BEH#4]
Hi

I've found your repository just now, after I have already setup my Nuc.
It's working almost everything except mSD card reader (I don't about Thunderbolt, becasue I don't have any device to test).

Any suggestion on how to let the card reader to work?

Thanks

**Comment by mbarbierato** [comment]
Hi,

use the Sinetek-rtsx.kext to enable the card Reader

**Comment by woody4165** [comment]
Thanks

I just tried, but as soon as I insert the mSD, it crashes and I got a reboot. If I start with the mSD inserted, it crashes during boot and it reboots....

PS:
Probably I I've downloaded an older version.
Downloading and installing [V.9.0](https://github.com/cholonam/Sinetek-rtsx/releases) works like a charm.




Just one question before closing this issue.
On my old iMac I'm using an app called [Macs Fan Control](https://crystalidea.com/macs-fan-control) that shows the fan speed.
On the NUC I can see only the CPU and disks temperatures, but not the fan spedd.
Do you know if there is any way to show it on the NUC ?

Thanks
