### ISSUE TITLE
Sleep wake up problem

### ISSUE THREAD

**Issue by LeonGus** [mbarbierato/Intel-NUC8i3BEH#5]
nuc8i5beh+bigsur 11.4
It will restart after sleep wakes up

Looking forward to your reply

**Comment by LeonGus** [comment]
I tried to change kernel/inquires/powertimeoutkernelpanel to true，

**Comment by LeonGus** [comment]
I tried to change **powertimeoutkernelpanic** to true， When you wake up again, it won't restart

**Comment by ftfniqpl** [comment]
same issue.
big sur 11.0.1 .
latest version itlwm 2.0.0 beta and intelbluetooth 1.3.
Automatically restart when you click sleep.

**Comment by mbarbierato** [comment]
> nuc8i5beh+bigsur 11.4
> It will restart after sleep wakes up
> 
> Looking forward to your reply

i've tried several times but i don't have this problem, attach the kp panic log or image

**Comment by mbarbierato** [comment]
> same issue.
> big sur 11.0.1 .
> latest version itlwm 2.0.0 beta and intelbluetooth 1.3.
> Automatically restart when you click sleep.

Try to update the airportitlwm kext to the  latest version 2.0 alpha or revert to 1.3 or use itlwm

**Comment by Lorys89** [comment]
use the latest EFI 0.7.0 in the release section of the repo, changing in section smbios with your serials if you use Apple's services.
if you mount an nvme you must use kext nvmefix.kext

**Comment by ftfniqpl** [comment]
> I tried to change **powertimeoutkernelpanic** to true， When you wake up again, it won't restart

Thanks.
When I modified this Kernel-->Quirks-->PowerTimeoutKernelPanic: false-->true, sleep wakeup seemed to work.

**Comment by LeonGus** [comment]
> > nuc8i5beh+bigsur 11.4
> > It will restart after sleep wakes up
> > Looking forward to your reply
> 
> i've tried several times but i don't have this problem, attach the kp panic log or image

hello， This is the log provided by the system after power on
`panic(cpu 0 caller 0xffffff80093d4e77): "AppleHDAHDMI_DPDriver::setPowerState(0xffffff9350263300 : 0xffffff7fa23d9a62, 0 -> 1) timed out after 10158 ms"@/System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/xnu/xnu-7195.121.3/iokit/Kernel/IOServicePM.cpp:5382
Backtrace (CPU 0), Frame : Return Address
0xffffffa073c8bac0 : 0xffffff8008c8e0dd 
0xffffffa073c8bb10 : 0xffffff8008dd4f33 
0xffffffa073c8bb50 : 0xffffff8008dc552a 
0xffffffa073c8bba0 : 0xffffff8008c32a2f 
0xffffffa073c8bbc0 : 0xffffff8008c8d8fd 
0xffffffa073c8bce0 : 0xffffff8008c8dbf3 
0xffffffa073c8bd50 : 0xffffff800949d81a 
0xffffffa073c8bdc0 : 0xffffff80093d4e77 
0xffffffa073c8be10 : 0xffffff80093d4799 
0xffffffa073c8be20 : 0xffffff80093ed8de 
0xffffffa073c8be60 : 0xffffff80093d3518 
0xffffffa073c8be80 : 0xffffff8008cd46c5 
0xffffffa073c8bef0 : 0xffffff8008cd5634 
0xffffffa073c8bfa0 : 0xffffff8008c3213e 

Process name corresponding to current thread: kernel_task
Boot args: -v chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
20F71

Kernel version:
Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
Kernel UUID: 52A1E876-863E-38E3-AC80-09BBAB13B752
KernelCache slide: 0x0000000008a00000
KernelCache base:  0xffffff8008c00000
Kernel slide:      0x0000000008a10000
Kernel text base:  0xffffff8008c10000
__HIB  text base: 0xffffff8008b00000
System model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 138695358384
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000000204ae33a78
  Sleep   : 0x0000001cd734822c 0x0000000b9f653372 0x0000000000000000
  Wake    : 0x0000001cfa15e195 0x00000000cffc7c3a 0x0000001cf302df4d


`

**Comment by mbarbierato** [comment]
Try to set in bios the primary video out to hdmi or thunderbolt

**Comment by LeonGus** [comment]
> Try to set in bios the primary video out to hdmi or thunderbolt

Thank you, your solution has solved the problem of computer sleep wake-up, but there is a strange phenomenon, when the computer sleep, the keyboard and mouse LED lights will be on and off repeatedly
