### ISSUE TITLE
HDMI and Thunderbolt cannot work at the same time

### ISSUE THREAD

**Issue by ftfniqpl** [mbarbierato/Intel-NUC8i3BEH#6]
Hi,

Both HDMI and Thunderbolt work independently, but only HDMI or Thunderbolt work when connected at the same time, it depends on who connects first.

Any suggestions on how to make them work at the same time?

Thanks.

**Comment by mbarbierato** [comment]
Set in bios primary output hdmi and secondary thunderbolt, it's work on the same time i've two monitor

**Comment by ftfniqpl** [comment]
When I set it like this, a green splash screen will appear on both screens.

**Comment by zearp** [comment]
Try with this frame buffer: https://github.com/zearp/Nucintosh/blob/d579f498dcc1170917aaa7b6ea37090594afe11f/EFI/OC/config.plist#L185-L211

It may need some more tweaks (disabling unused fb/connectors/etc) but it works for me on dual screens using usb-c + hdmi outputs. I didn't change anything in the BIOS, so whatever the default is there is what I got.

**Comment by zearp** [comment]
@ftfniqpl Can you try with this frame buffer?

https://github.com/zearp/Nucintosh/blob/d579f498dcc1170917aaa7b6ea37090594afe11f/EFI/OC/config.plist#L185-L211

It may need some more tweaks (disabling unused fb/connectors/etc) but it works for me on dual screens using usb-c + hdmi outputs. I didn't change anything in the BIOS, so whatever the default is there is what I got. Let me know it goes.
