### ISSUE TITLE
front 3.5mm headphone jack not work on Windows, but works on Mac OS Big Sur.

### ISSUE THREAD

**Issue by andyliu50** [mbarbierato/Intel-NUC8i3BEH#7]
This EFI is perfect for my NUC8 except the headphone jack.

I installed dual system on two separate disks, one is Windows 10, and the other is Mac OS Big Sur. If the Windows is booted from oc, the  headphone jack doesn't work. But if the Windows is booted without using oc, it just works. I'm new to oc, and can't figure it out. Hope can get help here.

**Comment by mbarbierato** [comment]
i tried with the default windows driver and the front headphone don't work, i updated the driver downloaded from intel website and the jack work

**Comment by mbarbierato** [comment]
link for intel nuc driver https://www.intel.it/content/www/it/it/products/sku/126150/intel-nuc-kit-nuc8i3beh/downloads.html

**Comment by andyliu50** [comment]
I uninstalled the audio driver from the computer management without rebooting, then the driver will be installed automatically, and the jack works. However, if I reboot the computer, the jack doesn't work. 

Now the workaround is to remove the driver manually after booting into the Windows. It looks like the audio driver is not loaded correctly during booting.

Anyway, thanks a lot!
